# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_electricityservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricityservice',
            name='provider',
            field=models.CharField(choices=[('EnergyAustralia', 'EnergyAustralia'), ('AGL', 'AGL'), ('RedEnergy', 'RedEnergy'), ('LumoEnergy', 'LumoEnergy'), ('OriginEnergy', 'OriginEnergy')], default='AGL', max_length=64, null=True),
        ),
    ]
