# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20160430_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileservice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlm.Person'),
        ),
    ]
