# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_broadbandservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadbandservice',
            name='monthlycost',
            field=models.FloatField(blank=True, default=80, null=True),
        ),
        migrations.AlterField(
            model_name='broadbandservice',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broadbandservice',
            name='provider',
            field=models.CharField(blank=True, choices=[('Optus', 'Optus'), ('Westnet', 'Westnet'), ('Telstra', 'Telstra')], default='Telstra', max_length=64, null=True),
        ),
    ]
