# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_securityservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityservice',
            name='interestedinsecuringhome',
            field=models.BooleanField(verbose_name='pizza'),
        ),
    ]
