# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20160508_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadbandservice',
            name='monthlycost',
            field=models.FloatField(blank=True, default=80, null=True, verbose_name='Monthly Cost'),
        ),
        migrations.AlterField(
            model_name='securityservice',
            name='expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry date of plan'),
        ),
        migrations.AlterField(
            model_name='securityservice',
            name='interestedinsecuringhome',
            field=models.BooleanField(verbose_name='Interested in securing home'),
        ),
        migrations.AlterField(
            model_name='securityservice',
            name='monthlycost',
            field=models.FloatField(blank=True, default=80, null=True, verbose_name='Monthly cost'),
        ),
        migrations.AlterField(
            model_name='securityservice',
            name='provider',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Provider'),
        ),
    ]
