# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0006_auto_20160508_1150'),
        ('services', '0010_auto_20160508_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, choices=[('Optus', 'Optus'), ('Westnet', 'Westnet'), ('Telstra', 'Telstra')], default='Telstra', max_length=64, null=True)),
                ('monthlycost', models.FloatField(blank=True, default=80, null=True, verbose_name='Monthly Cost')),
                ('expiry', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mlm.Person')),
            ],
        ),
    ]
