# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_phoneservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileservice',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobileservice',
            name='monthlycost',
            field=models.FloatField(blank=True, default=80, null=True),
        ),
    ]
