# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_csvupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookFriendUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.FileField(null=True, upload_to=b'')),
            ],
        ),
    ]
