# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0010_person_postcode'),
        ('dashboard', '0003_facebookfriendupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookfriendupload',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlm.Member'),
        ),
        migrations.AddField(
            model_name='facebookfriendupload',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='facebookfriendupload',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
