# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160612_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVUpload',
        ),
        migrations.RenameField(
            model_name='facebookfriendupload',
            old_name='friends',
            new_name='friendsfile',
        ),
    ]
