# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160612_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookfriendupload',
            name='friendsfile',
            field=models.FileField(null=True, upload_to=b'', verbose_name='PDF File'),
        ),
    ]
