# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofactivity', models.CharField(choices=[('Call', 'Call'), ('Business Opportunity Meeting', 'Business Opportunity Meeting'), ('One To Ten', 'One To Ten')], max_length=64)),
                ('notes', models.TextField(blank=True, max_length=2096, null=True)),
                ('timeofactivity', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=32)),
                ('lastname', models.CharField(default='', max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('businessid', models.CharField(max_length=10)),
                ('customerpoints', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[('Team Trainer', 'Team Trainer'), ('Qualified Team Trainer', 'Qualified Team Trainer'), ('Executive Team Trainer', 'Executive Team Trainer'), ('Executive Team Leader', 'Executive Team Leader'), ('Team Coordinator', 'Team Coordinator'), ('Regional Director', 'Regional Director'), ('Regional Vice President', 'Regional Vice President'), ('Senior Vice President', 'Senior Vice President')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Lead', 'Lead'), ('Customer', 'Customer'), ('Prospect', 'Prospect')], max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('streetno', models.CharField(max_length=12, null=True)),
                ('streetaddress', models.CharField(max_length=64, null=True)),
                ('suburb', models.CharField(max_length=32, null=True)),
                ('state', models.CharField(choices=[('QLD', 'QLD'), ('NSW', 'NSW'), ('WA', 'WA'), ('SA', 'SA'), ('TAS', 'TAS'), ('VIC', 'VIC')], max_length=32, null=True)),
                ('notes', models.TextField(blank=True, max_length=1024, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlm.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('established', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mlm.Team'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlm.Person'),
        ),
    ]
