# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, choices=[('QLD', 'QLD'), ('NSW', 'NSW'), ('WA', 'WA'), ('SA', 'SA'), ('TAS', 'TAS'), ('VIC', 'VIC')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetaddress',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetno',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='suburb',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
