# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0003_auto_20160501_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
