# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0004_person_facebooklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='typeofactivity',
            field=models.CharField(choices=[('Call', 'Call'), ('Business Opportunity Meeting', 'Business Opportunity Meeting'), ('One To Ten', 'One To Ten'), ('Meeting', 'Meeting')], max_length=64),
        ),
    ]
