# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0005_auto_20160501_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='businessid',
            field=models.CharField(max_length=10, verbose_name='Business ID #'),
        ),
        migrations.AlterField(
            model_name='member',
            name='customerpoints',
            field=models.IntegerField(blank=True, null=True, verbose_name='Customer Points'),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='', max_length=32, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='', max_length=32, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Team Trainer', 'Team Trainer'), ('Qualified Team Trainer', 'Qualified Team Trainer'), ('Executive Team Trainer', 'Executive Team Trainer'), ('Executive Team Leader', 'Executive Team Leader'), ('Team Coordinator', 'Team Coordinator'), ('Regional Director', 'Regional Director'), ('Regional Vice President', 'Regional Vice President'), ('Senior Vice President', 'Senior Vice President')], max_length=32, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebooklink',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Facebook profile link'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(blank=True, choices=[('QLD', 'QLD'), ('NSW', 'NSW'), ('WA', 'WA'), ('SA', 'SA'), ('TAS', 'TAS'), ('VIC', 'VIC')], max_length=32, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetaddress',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetno',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Street #'),
        ),
        migrations.AlterField(
            model_name='person',
            name='suburb',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Suburb/City'),
        ),
    ]
