# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0006_auto_20160508_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='timeofactivity',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
