# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0007_auto_20160509_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dateofactivity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
