# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0008_activity_dateofactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='dateandtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
