# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlm', '0009_activity_dateandtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
